repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: 3rd_party
      - id: end-of-file-fixer
  -   repo: local
      hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --cov-report term --cov=src src/ -vvv
        language: python
        pass_filenames: false
        always_run: true
