version: '3.7'

services:
    api:
        restart: always
        build: .
        image: api_model
        container_name: api_model
        ports:
            - "8000:8000"
        environment:
            - AWS_ACCESS_KEY_ID=minio
            - AWS_SECRET_ACCESS_KEY=minio123
            - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
            - MLFLOW_S3_ENDPOINT_URL=http://host.docker.internal:9000
        networks:
          - infra_default

networks:
  infra_default:
    external: true
