[tool.poetry]
name = "molliechallenge"
version = "0.1.0"
description = ""
authors = ["Gabriel Barbosa Soares <gabrielclimb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
jupyterlab = "^4.0.4"
pre-commit = "^3.3.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
ruff = "^0.0.283"
black = "^23.7.0"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
